### PR TITLE
#457 allow dependency to be installed on non mac os

### PR DESCRIPTION
**Pull request by michaelBenin**

### CODE REVIEW

**Comment by cgcardona** [comment]
Can you please provide some details for this PR? Is it only a yarn.lock change? Why does this change make it possible to install the deps on non-macos?

**Comment by cgcardona** [comment]
ping @michaelBenin Can you please provide some details for this PR? Is it only a yarn.lock change? Why does this change make it possible to install the deps on non-macos?

**Comment by michaelBenin** [comment]
https://github.com/ava-labs/avalanchejs/issues/457 - See issue linked.

**Comment by michaelBenin** [comment]
If anyone else runs into this issue switch to pnpm https://pnpm.io/installation

**Pull request closed without merging**
